sudo: required
services:
  - docker

before_install:
  - docker build -t chrishao/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chrishao/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker_react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-664257890542"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

